module.exports = {
    arrowParens: 'always',
    bracketSameLine: false,
    bracketSpacing: true,
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'strict',
    trailingComma: 'es5',
    tabWidth: 4,
    printWidth: 120,
    semi: true,
    singleQuote: true,
    jsxSingleQuote: true,
    importOrder: ['^components/(.*)$', '^[./]'],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
};
